// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGZiaa0KqDgHyLk89abFQCgh4oUBqvJzc',
    appId: '1:870194509289:web:6842ed3a17769eb6ecc778',
    messagingSenderId: '870194509289',
    projectId: 'aerocab-5d474',
    authDomain: 'aerocab-5d474.firebaseapp.com',
    storageBucket: 'aerocab-5d474.firebasestorage.app',
    measurementId: 'G-TEE6BCMN8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgmNiik5lKCsWNPSuRsjhyUI50g-jFBF4',
    appId: '1:870194509289:android:9e0700fc465d8919ecc778',
    messagingSenderId: '870194509289',
    projectId: 'aerocab-5d474',
    storageBucket: 'aerocab-5d474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf86rMa-y1gz-m60jg11GKl3RUEaGmzFE',
    appId: '1:870194509289:ios:9e7b43e5fc1e2d18ecc778',
    messagingSenderId: '870194509289',
    projectId: 'aerocab-5d474',
    storageBucket: 'aerocab-5d474.firebasestorage.app',
    iosBundleId: 'com.ugurozbidak.aerocabapp',
  );
}
